metadata:
  app_name: GNOME Calculator
  calibrated_date: '2026-02-19'
  screen_resolution: 1280x1024
  coordinate_system: absolute
  recorded_points: 24
buttons:
  backspace:
  - 112
  - 286
  paren_open:
  - 179
  - 288
  paren_close:
  - 247
  - 287
  mod:
  - 319
  - 287
  pi:
  - 385
  - 285
  digit_7:
  - 112
  - 334
  digit_8:
  - 177
  - 336
  digit_9:
  - 249
  - 333
  divide:
  - 315
  - 338
  sqrt:
  - 384
  - 337
  digit_4:
  - 115
  - 386
  digit_5:
  - 180
  - 382
  digit_6:
  - 247
  - 382
  multiply:
  - 314
  - 384
  square:
  - 384
  - 382
  digit_1:
  - 112
  - 428
  digit_2:
  - 183
  - 431
  digit_3:
  - 249
  - 433
  minus:
  - 317
  - 433
  equals:
  - 385
  - 453
  digit_0:
  - 109
  - 481
  decimal:
  - 179
  - 478
  percent:
  - 250
  - 479
  plus:
  - 315
  - 480
